### ISSUE TITLE
Array stride in uniform address space

### ISSUE THREAD

**Issue by Andrewp2** [teoxoy/encase#43]
Today I was trying to write this struct to a uniform buffer:

```rust
#[derive(ShaderType)]
pub struct MortonUniforms {
    lut: [u32; 4608],
    size_lut: [u32; 1 << (extended_morton_coder::SIZE_LUT_NUMBER_OF_BITS + 1)],
    morton_index_scale: f32,
    offset: Vec3,
    size_multiplier: f32,
    multiplier: Vec3,
}
```

This doesn't work because of `lut` and `size_lut`, with this error:

`thread 'main' panicked at 'array stride must be a multiple of 16 (current stride: 4)', C:\Users\andre\.cargo\registry\src\index.crates.io-6f17d22bba15001f\encase-0.6.1\src\types\array.rs:47:17`

I saw issue #40 , and that the solution is to "create your own newtype around an array and [...] derive them" using the `impl_vector` macro, but I was confused on how to use that macro or if it made sense in my situation considering I have a lot more than 4 elements.

**Comment by teoxoy** [comment]
In issue #40 they were trying to write a vec4 but in your case you do want to write an array. The issue is that the spec requires elements of arrays (in the uniform address space) to be at least 16 bytes. Based on the amount of elements you want to write, I'd pack them in `vec4`s (ex. `lut: [UVec4; 1152],`).
